/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webp;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.ImageWriteParam;
import javax.imageio.ImageWriter;
import javax.imageio.stream.FileImageInputStream;
import javax.imageio.stream.FileImageOutputStream;

import org.junit.Test;

import com.luciad.imageio.webp.WebPWriteParam;

public class WebPLibraryTest {
  @Test
  public void testReadingWebP() throws IOException {

    File fileIn = new File("test_pic/test.webp");
    File fiftyPercent = new File("test_pic/tree_50.webp");
    File lossless = new File("test_pic/tree_100.webp");

    fiftyPercent.delete();
    lossless.delete();
    ImageReader reader = ImageIO.getImageReadersByMIMEType("image/webp").next();
    FileImageInputStream is = new FileImageInputStream(fileIn);
    ImageReadParam readParam = reader.getDefaultReadParam();
    reader.setInput(is);
    

    BufferedImage image = reader.read(0, readParam);

    Float q = .5f;
    ImageWriter writer = ImageIO.getImageWritersByMIMEType("image/webp").next();
    WebPWriteParam writeParam = new WebPWriteParam(writer.getLocale());

    if (q == 1) {
      writeParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
      writeParam.setCompressionType("Lossless");

    } else {
      writeParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
      writeParam.setCompressionType("Lossy");
      writeParam.setCompressionQuality(q);
    }

    writer.setOutput(new FileImageOutputStream(fiftyPercent));
    writer.write(null, new IIOImage(image, null, null), writeParam);
    writer.dispose();
    
    

     writer = ImageIO.getImageWritersByMIMEType("image/webp").next();
     writeParam = new WebPWriteParam(writer.getLocale());

 
      writeParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
      writeParam.setCompressionType("Lossless");



    writer.setOutput(new FileImageOutputStream(lossless));
    writer.write(null, new IIOImage(image, null, null), writeParam);
    writer.dispose();
    
    
    

  }
}
